apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: customer-management
data:
  # Cấu hình chung
  SPRING_APPLICATION_NAME: "customer-service"
  STATISTICS_APPLICATION_NAME: "statistics-service"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

  # Cấu hình API Gateway
  API_GATEWAY_PORT: "8080"
  CUSTOMER_SERVICE_HOST: "customer-service"
  CUSTOMER_SERVICE_PORT: "8081"
  STATISTICS_SERVICE_HOST: "statistics-service"
  STATISTICS_SERVICE_PORT: "8082"

  # URL Service
  CUSTOMER_SERVICE_URL: "http://customer-service:8081"

  # Redis Configuration
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_CACHE_TYPE: "redis"
  SPRING_CACHE_REDIS_TIME_TO_LIVE: "600000"
